name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build


  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build
  createfeature:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "MYBUILDDATE=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create feature branch
      run: git checkout -b feature/${{ env.MYBUILDDATE }}
    - name: Push new branch
      run: git push origin feature/${{ env.MYBUILDDATE }}
